"""add tasks table

Revision ID: 045da95e593a
Revises: 19a079e39a76
Create Date: 2026-05-22 15:44:07.425633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045da95e593a'
down_revision: Union[str, Sequence[str], None] = '19a079e39a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('due_datetime', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('show_from_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'show_from_date')
    op.drop_column('tasks', 'due_datetime')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
