"""add_notes_table

Revision ID: 1335a27dd015
Revises: 5ef344973624
Create Date: 2026-05-23 17:19:56.883441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1335a27dd015'
down_revision: Union[str, Sequence[str], None] = '5ef344973624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_date')
    )
    op.create_table('single_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dates', sa.Column('full_date', sa.Date(), nullable=False))
    op.add_column('dates', sa.Column('in_month', sa.Boolean(), nullable=True))
    op.drop_column('dates', '_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('dates', 'in_month')
    op.drop_column('dates', 'full_date')
    op.drop_table('single_dates')
    op.drop_table('notes')
    # ### end Alembic commands ###
