"""change tasks table split due_datetime to due_date and due_time

Revision ID: 3f2de68f5d17
Revises: d612add76b01
Create Date: 2026-05-22 15:57:04.642647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f2de68f5d17'
down_revision: Union[str, Sequence[str], None] = 'd612add76b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('due_time', sa.Time(), nullable=True))
    op.drop_column('tasks', 'due_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'due_time')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
